Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -1,41 +1,36 @@
-# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
-
 name: Node.js CI
 
 on:
   push:
-    branches: [ "main" ]
+    branches: ["main"]
   pull_request:
-    branches: [ "main" ]
+    branches: ["main"]
 
 jobs:
-  build:
-
+  run-prebuilt:
     runs-on: self-hosted
 
-    strategy:
-      matrix:
-        node-version: [20.x]
-        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
-
     steps:
-    - uses: actions/checkout@v4
-    - name: List files in mes-api
-      run: ls -la mes-api/
-    - name: Use Node.js ${{ matrix.node-version }}
-      uses: actions/setup-node@v4
-      with:
-        node-version: ${{ matrix.node-version }}
-        cache: 'npm'
-        cache-dependency-path: mes-api/package-lock.json' # Try glob pattern
-    - name: Install dependencies
-      run: cd mes-api && npm ci
-    - name: Create .env file
-      run: |
-        cd mes-api
-        touch .env
-        echo "${{ secrets.PROD_ENV_FILES }}" > .env  # Create .env in mes-api
-    - name: Run the app
-      run: cd mes-api && npm start
-        
+      - uses: actions/checkout@v4
+
+      - name: Verify build folder exists
+        run: |
+          if [ -d "mes-api/build" ]; then
+            echo "Build directory exists"
+          else
+            echo "Build directory NOT found"
+            exit 1
+          fi
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: 20
+
+      - name: Create .env file
+        working-directory: mes-api
+        run: printf "%s" "${{ secrets.PROD_ENV_FILES }}" > .env
+
+      - name: Run prebuilt app
+        working-directory: mes-api
+        run: node build/index.js
